import { expect, test } from "@playwright/test";
import { createSession, deleteSession, openRole } from "../e2e/helpers";
test("captura da tela do jogador", async ({ browser, page }) => {
  test.setTimeout(150_000);
  const links = await createSession(page, "progressivo");
  const a = await openRole(browser, links.playerA, { width: 1440, height: 900 });
  const b = await openRole(browser, links.playerB, { width: 1440, height: 900 });
  await expect(a.page.getByRole("log")).toBeVisible({ timeout: 30_000 });
  await expect(b.page.getByRole("log")).toBeVisible({ timeout: 30_000 });
  await b.page.getByLabel("Mensagem").fill("boa partida! você joga muito bem");
  await b.page.getByLabel("Mensagem").press("Enter");
  await expect(a.page.getByRole("log")).toContainText("boa partida", { timeout: 15_000 });
  await a.page.getByLabel("Mensagem").fill("valeu!! bora mais uma?");
  await a.page.getByLabel("Mensagem").press("Enter");
  await b.page.getByLabel("Mensagem").fill("bora");
  await a.page.waitForTimeout(2500);
  await a.page.screenshot({ path: "docs/capturas/00-jogo-chat.png" });
  await a.page.setViewportSize({ width: 390, height: 844 });
  await a.page.waitForTimeout(1500);
  await a.page.screenshot({ path: "docs/capturas/00-jogo-chat-mobile.png" });
  await Promise.all([a.context.close(), b.context.close()]);
  await deleteSession(page);
});
